### ISSUE TITLE
Expected Option type for id

### ISSUE THREAD

**Issue by eribol** [weiznich/wundergraph#20]
```
#[derive(Queryable, Identifiable, PartialEq, Debug, Serialize,WundergraphEntity,
         WundergraphFilter, Associations)]
#[table_name = "users"]
pub struct User {
    pub id: i32,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub username: Option<String>,
    pub email: Option<String>,
    pub password: Option<String>,
    pub date_join: NaiveDateTime,
    pub last_login: Option<NaiveDateTime>,
    pub is_active: Option<bool>,
    pub is_staff: Option<bool>,
    pub is_admin: Option<bool>,
    pub tel: Option<String>,
    pub gender:Option<String>,
    pub img:Option<String>,
}
```

schema.rs:
```
table! {
    users (id) {
        id -> Integer,
        first_name -> Nullable<Varchar>,
        last_name -> Nullable<Varchar>,
        username -> Nullable<Varchar>,
        email -> Nullable<Varchar>,
        password -> Nullable<Varchar>,
        date_join -> Timestamp,
        last_login -> Nullable<Timestamp>,
        is_active -> Nullable<Bool>,
        is_staff -> Nullable<Bool>,
        is_admin -> Nullable<Bool>,
        tel -> Nullable<Varchar>,
        gender -> Nullable<Varchar>,
        img -> Nullable<Varchar>,
    }
}
```
And it says;

> pub id: i32,
>               ^^ expected i32, found enum `std::option::Option`

**Comment by weiznich** [comment]
Try removing the derive for `WundergraphFilter`.
The example in the readme is totally out of sync with the repo. Look into wundergraph_example or wundergraph_bench for working code.

**Comment by eribol** [comment]
Thank you. 

I will look at them but i am using actix-web 1.0 and example is for 0.7 which its using Handler for database. Just say it :)

**Comment by weiznich** [comment]
> I will look at them but i am using actix-web 1.0 and example is for 0.7 which its using Handler for database. Just say it :)

That only changes the juniper/diesel integration stuff into actix, not the usage of wundergraph itself.

**Comment by weiznich** [comment]
Fixed the wrong documentation here as part of the release. This should work now if you follow the example in the readme.
