### ISSUE TITLE
Fix small issues with `wundergraph_cli`

### ISSUE THREAD

**Issue by weiznich** [weiznich/wundergraph#25]
Sometimes the generated file contains structs which may contain types (for example `uuid::Uuid` or `chrono::DateTime`) that are nowt in the prelude. `wundergraph_cli` does nto generate the required imports there. Find a way to do that.
I think the easiest way to fix that is to just generate fully qualified paths instead of using only the type name there. Type mapping is happening [here](https://github.com/weiznich/wundergraph/blob/97337651b9866b87ce2faf420c4f5d2aec072190/wundergraph_cli/src/print_schema/print_helper.rs#L398-L406)

**Comment by naufraghi** [comment]
I can work on this
