### ISSUE TITLE
cli when generating schema Jsonb types must be converted to serde_json::Value

### ISSUE THREAD

**Issue by Farkal** [weiznich/wundergraph#30]
It would be even better to add use serde_json::Value as JsonValue

**Comment by weiznich** [comment]
As juniper does not support `serde_json::Value` there is no straight forward way to implement that. Therefore I would prefer to not do that in wundergraph itself. 
That said it is possible to implement support for `serde_json::Value` by using a new type wrapper and basically implementing a custom type, similar to the enum in wundergraph_example.
