### ISSUE TITLE
How to handle authentication and authorization with fine-grained permissions?

### ISSUE THREAD

**Issue by frol** [weiznich/wundergraph#32]
Is there an example of the subject?

P.S. Thank you for your work on the project!

**Comment by weiznich** [comment]
There is currently no example for this, but the [`QueryModifier`](https://docs.rs/wundergraph/0.1.1/wundergraph/prelude/trait.QueryModifier.html) trait is designed to handle this use case.

Basically you would use a custom context type that contains informations required to authenticate the user and then implement the `QueryModifier` trait to modify (or abort) the generated query with those information.

**Comment by insanebaba** [comment]
Hi @weiznich , Can you please add this in the wundergraph_example as It seem this is a recurring task that everyone needs. I think this is also part of the common boilerplate with juniper. Thank you

**Comment by weiznich** [comment]
@insanebaba Please think about your wording. I perceive the wording "Can you please do this or that" towards someone, who spends it free time working on open source projects as rude.

That said: I would be happy to receive a PR doing that, but I don't see that I have the time and motivation to work on this anytime soon.

**Comment by frol** [comment]
@weiznich Hmm, I am sure @insanebaba did not mean to be rude (he used a question with "please", detailed on how why he thinks it might be important for the newcomers and thanked at the end).

I think many of us rely on the authors as the source of wisdom especially for such design tasks as authentication & authorization processes. Sure, authors are busy with other tasks, but it is fine to ask just in case the author happens to build a project where they solved the puzzle.

Cheers! Thanks for your great work!
