### ISSUE TITLE
Order by not working

### ISSUE THREAD

**Issue by andrejohansson** [weiznich/wundergraph#41]
Is there anything special i need to do to get ordering to work?

Seen in this picture, I'm trying to order by id.  But I've tried different columns with different datatypes (strings, timestamps) but I get the same result. No sorting is done at all.

Thank you for a kick ass crate by the way!

![image](https://user-images.githubusercontent.com/2828428/77343895-b3c44c00-6d32-11ea-9987-e239b710e207.png)

**Comment by weiznich** [comment]
Can you get the corresponding sql query by enabling the `debug` feature for wundergraph and register some crate the gives out calls to `log::debug!()` for example `env_logger`.

**Comment by andrejohansson** [comment]
Hmm, seems like no order by gets generated at all:

```[2020-03-23T22:12:42Z DEBUG wundergraph::query_builder::selection] Query { sql: "SELECT \"events\".\"id\", \"events\".\"name\",  NULL ,  NULL ,  NULL ,  NULL ,  NULL , \"events\".\"start_time\",  NULL ,  NULL ,  NULL ,  NULL  FROM \"events\"", binds: [] }```

Something wrong with my entity perhaps? Some missing attribute...like "orderable" or something similar?

```rust
#[derive(Clone, Debug, Identifiable, Queryable, Associations, WundergraphEntity)]
#[table_name = "events"]
pub struct Event  {
    pub id: i32,

    pub name: String,    
    pub description: Option<String>,

    pub image_url: Option<String>,
    pub location_url:  Option<String>,
    
    pub base_price: Option<i32>,
    pub unit_price: Option<i32>,
    
    pub start_time: chrono::DateTime<Utc>,
    pub end_time: Option<chrono::DateTime<Utc>>,
    
    pub event_type: EventTypeEnum,
    
    pub address_id: Option<i32>,
    #[column_name = "address_id"]
    pub address: HasOne<i32, Address>,

    pub options: HasMany<EventResponseOption, rel_events_response_options::event_id>,
}
```

**Comment by weiznich** [comment]
Hmm, that is interesting, as the [corresponding test cases](https://github.com/weiznich/wundergraph/blob/a9ab2d3f62301e785ca4f0d742f2d62297d01532/wundergraph/tests/order.rs) for order clauses seems to work. Can you put together a small example that reproduces the issue?

**Comment by andrejohansson** [comment]
Don´t know about small, but [here](https://send.firefox.com/download/c005a4fe54ad7035/#8eu9s2TykSdIRiGCOLgfgg) is the project. I sent you the password in private.

Nevermind, no pm function found on github. Must be getting tired here. 😄 
Password is: ``myweddingpage``

**Comment by weiznich** [comment]
I think I've found the problem. Order is taking a list of order expressions, so you need to pass an array there. I've no data to test, but the following graphql request generates the expected sql:

```graphql
{
  Events(order: [{column: id, direction: ASC}]) {
    id
    name
    start_time
  }
}
```

That said, I still consider this to be a bug, because a invalid request should generate an error and not silently drop something.

**Comment by andrejohansson** [comment]
Thank you!

I can confirm that using an array works for me.
